/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/circuit.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.014']} />
      <group position={[-0.01, 0, -0.95]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[1, 1.18, 1.22]}>
        <mesh geometry={nodes.Cylinder002_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cylinder002_2.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cylinder002_3.geometry} material={materials['Material.003']} />
      </group>
      <mesh
        geometry={nodes.Sphere002.geometry}
        material={materials['Material.019']}
        position={[2.6, 0.22, -2]}
        scale={0.15}
      />
      <mesh
        geometry={nodes.Cylinder002.geometry}
        material={nodes.Cylinder002.material}
        position={[2.52, 0.12, -2]}
        scale={[0.43, 0.13, 0.43]}
      />
      <mesh
        geometry={nodes.Cylinder003.geometry}
        material={nodes.Cylinder003.material}
        position={[2.68, 0.12, -2]}
        scale={[0.43, 0.13, 0.43]}
      />
      <mesh
        name="Sphere001"
        geometry={nodes.Sphere001.geometry}
        material={nodes.Sphere001.material}
        position={[3.35, 0, 0]}
        rotation={[0, -1.56, 0]}
        scale={[0.8, 0.8, 0.8]}
      />
      <mesh
        name="Sphere003"
        geometry={nodes.Sphere003.geometry}
        material={nodes.Sphere003.material}
        position={[2.51, 0, 0]}
        rotation={[0, -1.57, 0]}
        scale={[0.8, 0.8, 0.8]}
      />
      <mesh
        name="Sphere004"
        geometry={nodes.Sphere004.geometry}
        material={nodes.Sphere004.material}
        position={[1.66, 0, 0]}
        rotation={[0, -1.57, 0]}
        scale={[0.8, 0.8, 0.8]}
      />
      <mesh
        name="Sphere005"
        geometry={nodes.Sphere005.geometry}
        material={nodes.Sphere005.material}
        position={[0.82, 0, 0]}
        rotation={[Math.PI, -1.57, Math.PI]}
        scale={[0.8, 0.8, 0.8]}
      />
      <mesh
        name="Sphere006"
        geometry={nodes.Sphere006.geometry}
        material={nodes.Sphere006.material}
        position={[0.01, 0, -0.08]}
        rotation={[Math.PI, -0.15, Math.PI]}
        scale={0.8}
      />
      <mesh
        name="Sphere007"
        geometry={nodes.Sphere007.geometry}
        material={nodes.Sphere007.material}
        position={[0, 0, -0.92]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.8}
      />
      <mesh
        name="Sphere008"
        geometry={nodes.Sphere008.geometry}
        material={nodes.Sphere008.material}
        position={[0, 0, -1.77]}
        rotation={[-Math.PI, 0.01, -Math.PI]}
        scale={[0.8, 0.8, 0.8]}
      />
      <mesh
        name="Sphere009"
        geometry={nodes.Sphere009.geometry}
        material={nodes.Sphere009.material}
        position={[0.65, 0, -2]}
        rotation={[-Math.PI, 1.57, -Math.PI]}
        scale={[0.8, 0.8, 0.8]}
      />
      <mesh
        name="Sphere010"
        geometry={nodes.Sphere010.geometry}
        material={nodes.Sphere010.material}
        position={[1.49, 0, -2]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.8}
      />
      <mesh
        name="Sphere011"
        geometry={nodes.Sphere011.geometry}
        material={nodes.Sphere011.material}
        position={[2.34, 0, -2]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.8, 0.8, 0.8]}
      />
      <mesh
        name="Sphere012"
        geometry={nodes.Sphere012.geometry}
        material={nodes.Sphere012.material}
        position={[3.18, 0, -2]}
        rotation={[0, 1.57, 0]}
        scale={[0.8, 0.8, 0.8]}
      />
      <mesh
        name="Sphere013"
        geometry={nodes.Sphere013.geometry}
        material={nodes.Sphere013.material}
        position={[3.99, 0, -1.89]}
        rotation={[0, 0.28, 0]}
        scale={[0.8, 0.8, 0.8]}
      />
      <mesh
        name="Sphere014"
        geometry={nodes.Sphere014.geometry}
        material={nodes.Sphere014.material}
        position={[4.01, 0, -1.04]}
        scale={[0.8, 0.8, 0.8]}
      />
      <mesh
        name="Sphere015"
        geometry={nodes.Sphere015.geometry}
        material={nodes.Sphere015.material}
        position={[4, 0, -0.29]}
        rotation={[0, -0.04, 0]}
        scale={[0.8, 0.8, 0.8]}
      />
      <mesh
        geometry={nodes.Sphere.geometry}
        material={nodes.Sphere.material}
        position={[1.84, 0, 0]}
        scale={[0.04, 0.04, 0.04]}
      />
      <mesh
        geometry={nodes.Sphere016.geometry}
        material={nodes.Sphere016.material}
        position={[1.58, 0, 0]}
        scale={[0.04, 0.04, 0.04]}
      />
      <mesh
        geometry={nodes.handle.geometry}
        material={nodes.handle.material}
        position={[1.58, 0, 0.01]}
        rotation={[0, 0, -1.57]}
        scale={[1.16, 0.36, 1.16]}
      />
    </group>
  )
}

useGLTF.preload('/circuit.glb')
